In [1]:
import numpy as np
import pandas as pd

In [2]:
sf1_numbers = pd.read_csv('sf1_numbers.csv')
sf1_percentages = pd.read_csv('sf1_percentages.csv')

acs1_numbers = pd.read_csv('acs1_numbers.csv')
acs1_percentages = pd.read_csv('acs1_percentages.csv')

social_numbers = pd.read_csv('social_numbers.csv')
social_percentages = pd.read_csv('social_percentages.csv')

economic_numbers = pd.read_csv('economic_numbers.csv')
economic_percentages = pd.read_csv('economic_percentages.csv')

housing_numbers = pd.read_csv('housing_numbers.csv')
housing_percentages = pd.read_csv('housing_percentages.csv')

predictions = pd.read_csv('predictions.csv')

In [3]:
dfs = [sf1_numbers,sf1_percentages,acs1_numbers,acs1_percentages,social_numbers,social_percentages,economic_numbers,
      economic_percentages,housing_numbers,housing_percentages]

for df in dfs:
    df.drop(['Unnamed: 0'], axis=1, inplace=True)
    df['Democrat'] = predictions['Democrat']

In [4]:
sf1_percentages.head()

,Percent; SEX AND AGE - Total population,Percent; SEX AND AGE - Total population - Under 5 years,Percent; SEX AND AGE - Total population - 5 to 9 years,Percent; SEX AND AGE - Total population - 10 to 14 years,Percent; SEX AND AGE - Total population - 15 to 19 years,Percent; SEX AND AGE - Total population - 20 to 24 years,Percent; SEX AND AGE - Total population - 25 to 29 years,Percent; SEX AND AGE - Total population - 30 to 34 years,Percent; SEX AND AGE - Total population - 35 to 39 years,Percent; SEX AND AGE - Total population - 40 to 44 years,...,Percent; HOUSING OCCUPANCY - Total housing units - Vacant housing units - For rent,"Percent; HOUSING OCCUPANCY - Total housing units - Vacant housing units - Rented, not occupied",Percent; HOUSING OCCUPANCY - Total housing units - Vacant housing units - For sale only,"Percent; HOUSING OCCUPANCY - Total housing units - Vacant housing units - Sold, not occupied","Percent; HOUSING OCCUPANCY - Total housing units - Vacant housing units - For seasonal, recreational, or occasional use",Percent; HOUSING OCCUPANCY - Total housing units - Vacant housing units - All other vacants,Percent; HOUSING TENURE - Occupied housing units,Percent; HOUSING TENURE - Occupied housing units - Owner-occupied housing units,Percent; HOUSING TENURE - Occupied housing units - Renter-occupied housing units,Democrat
0,100.0,6.5,6.6,6.9,7.1,6.3,6.3,6.1,6.3,6.4,...,4.9,0.2,1.9,0.4,6.4,4.0,100.0,69.7,30.3,0
1,100.0,6.5,6.6,6.9,7.1,6.3,6.3,6.1,6.3,6.4,...,4.9,0.2,1.9,0.4,6.4,4.0,100.0,69.7,30.3,0
2,100.0,6.5,6.5,6.6,7.0,7.0,6.8,6.4,6.6,6.4,...,3.5,0.2,1.4,0.4,2.5,4.7,100.0,67.7,32.3,0
3,100.0,6.2,6.2,6.6,7.5,8.1,6.4,6.1,6.4,6.5,...,3.5,0.2,1.8,0.5,4.2,4.4,100.0,69.9,30.1,0
4,100.0,6.3,6.5,6.7,6.8,5.8,5.8,5.9,6.5,6.7,...,2.7,0.1,1.5,0.6,2.8,5.3,100.0,74.0,26.0,0

In [5]:
sf1_numbers_corr = sf1_numbers.corr()
sf1_percentages_corr = sf1_percentages.corr()

acs1_numbers_corr = acs1_numbers.corr()
acs1_percentages_corr = acs1_percentages.corr()

social_numbers_corr = social_numbers.corr()
social_percentages_corr = social_percentages.corr()

economic_numbers_corr = economic_numbers.corr()
economic_percentages_corr = economic_percentages.corr()

housing_numbers_corr = housing_numbers.corr()
housing_percentages_corr = housing_percentages.corr()

In [6]:
corr_dfs = [sf1_numbers_corr,sf1_percentages_corr,acs1_numbers_corr,acs1_percentages_corr,social_numbers_corr,social_percentages_corr,economic_numbers_corr,
           economic_percentages_corr,housing_numbers_corr,housing_percentages_corr]

In [7]:
len(sf1_percentages_corr)

176

In [8]:
def make_corr_table(table): 
    df = pd.DataFrame()

    for i in range(len(table.columns)):
        app = pd.DataFrame()

        app['Column'] = table.columns
        app['Row'] = table.columns[i]
        app['Corr'] = table.lookup(app['Row'],app['Column'])
        app['Col_Dem'] = [table.loc[col,'Democrat'] for col in app['Column']]
        app['Row_Dem'] = [table.loc[row, 'Democrat'] for row in app['Row']]
        df = df.append(app)
    
    return df

In [9]:
sf1_numbers_comp = make_corr_table(sf1_numbers_corr)
sf1_percentages_comp = make_corr_table(sf1_percentages_corr)

acs1_numbers_comp = make_corr_table(acs1_numbers_corr)
acs1_percentages_comp = make_corr_table(acs1_percentages_corr)

social_numbers_comp = make_corr_table(social_numbers_corr)
social_percentages_comp = make_corr_table(social_percentages_corr)

economic_numbers_comp = make_corr_table(economic_numbers_corr)
economic_percentages_comp = make_corr_table(economic_percentages_corr)

housing_numbers_comp = make_corr_table(housing_numbers_corr)
housing_percentages_comp = make_corr_table(housing_percentages_corr)

In [10]:
sf1_percentages_comp.head()

,Column,Row,Corr,Col_Dem,Row_Dem
0,Percent; SEX AND AGE - Total population,Percent; SEX AND AGE - Total population,NaN,NaN,NaN
1,Percent; SEX AND AGE - Total population - Unde...,Percent; SEX AND AGE - Total population,NaN,0.051197,NaN
2,Percent; SEX AND AGE - Total population - 5 to...,Percent; SEX AND AGE - Total population,NaN,-0.095738,NaN
3,Percent; SEX AND AGE - Total population - 10 t...,Percent; SEX AND AGE - Total population,NaN,-0.124623,NaN
4,Percent; SEX AND AGE - Total population - 15 t...,Percent; SEX AND AGE - Total population,NaN,0.062873,NaN

In [11]:
comp_dfs = [sf1_numbers_comp,sf1_percentages_comp,acs1_numbers_comp,acs1_percentages_comp,social_numbers_comp,social_percentages_comp,
            economic_numbers_comp,economic_percentages_comp,housing_numbers_comp,housing_percentages_comp]

In [12]:
len(sf1_percentages_comp)

30976

In [13]:
for df in comp_dfs:
    df.reset_index(inplace=True)
    df.drop(['index'], axis=1, inplace=True)
    drop_rows = []
    for index, row in df.iterrows():
        if row[0] == row[1] or row[0] == 'Democrat' or row[1] == 'Democrat':
            drop_rows.append(index)
    df.drop(drop_rows, axis=0, inplace=True)

In [14]:
for df in comp_dfs:
    df['Corr'] = np.abs(df['Corr'])
    df['Col_Dem'] = np.abs(df['Col_Dem'])
    df['Row_Dem'] = np.abs(df['Row_Dem'])

In [15]:
for df in comp_dfs:
    df.dropna(inplace=True)

In [16]:
len(sf1_percentages_comp)

27722

In [17]:
def remove_correlates(table):
    drop_variables = []
    
    for index, row in table.iterrows():
        if row[2] >= 1.0:
            if row[3] > row[4]:
                drop_variables.append(row[1])
            else:
                drop_variables.append(row[0])
                
    return drop_variables

In [18]:
sf1_numbers_drop = remove_correlates(sf1_numbers_comp)
sf1_percentages_drop = remove_correlates(sf1_percentages_comp)

acs1_numbers_drop = remove_correlates(acs1_numbers_comp)
acs1_percentages_drop = remove_correlates(acs1_percentages_comp)

social_numbers_drop = remove_correlates(social_numbers_comp)
social_percentages_drop = remove_correlates(social_percentages_comp)

economic_numbers_drop = remove_correlates(economic_numbers_comp)
economic_percentages_drop = remove_correlates(economic_percentages_comp)

housing_numbers_drop = remove_correlates(housing_numbers_comp)
housing_percentages_drop = remove_correlates(housing_percentages_comp)

In [19]:
sf1_numbers_drop = list(set(sf1_numbers_drop))
sf1_percentages_drop = list(set(sf1_percentages_drop))

acs1_numbers_drop = list(set(acs1_numbers_drop))
acs1_percentages_drop = list(set(acs1_percentages_drop))

social_numbers_drop = list(set(social_numbers_drop))
social_percentages_drop = list(set(social_percentages_drop))

economic_numbers_drop = list(set(economic_numbers_drop))
economic_percentages_drop = list(set(economic_percentages_drop))

housing_numbers_drop = list(set(housing_numbers_drop))
housing_percentages_drop = list(set(housing_percentages_drop))

In [20]:
sf1_numbers_short = sf1_numbers.drop(sf1_numbers_drop, axis=1)
sf1_percentages_short = sf1_percentages.drop(sf1_percentages_drop, axis=1)

acs1_numbers_short = acs1_numbers.drop(acs1_numbers_drop, axis=1)
acs1_percentages_short = acs1_percentages.drop(acs1_percentages_drop, axis=1)

social_numbers_short = social_numbers.drop(social_numbers_drop, axis=1)
social_percentages_short = social_percentages.drop(social_percentages_drop, axis=1)

economic_numbers_short = economic_numbers.drop(economic_numbers_drop, axis=1)
economic_percentages_short = economic_percentages.drop(economic_percentages_drop, axis=1)

housing_numbers_short = housing_numbers.drop(housing_numbers_drop, axis=1)
housing_percentages_short = housing_percentages.drop(housing_percentages_drop, axis=1)

In [21]:
sf1_numbers_short.drop(['Democrat'],axis=1, inplace=True)
sf1_percentages_short.drop(['Democrat'], axis=1, inplace=True)

acs1_numbers_short.drop(['Democrat'], axis=1, inplace=True)
acs1_percentages_short.drop(['Democrat'], axis=1, inplace=True)

social_numbers_short.drop(['Democrat'], axis=1, inplace=True)
social_percentages_short.drop(['Democrat'], axis=1, inplace=True)

economic_numbers_short.drop(['Democrat'], axis=1, inplace=True)
economic_percentages_short.drop(['Democrat'], axis=1, inplace=True)

housing_numbers_short.drop(['Democrat'], axis=1, inplace=True)
housing_percentages_short.drop(['Democrat'], axis=1, inplace=True)

In [22]:
print(len(sf1_percentages_short.columns))
print(len(sf1_percentages.columns))

167
176

In [23]:
sf1_numbers_short.head()

,Number; SEX AND AGE - Total population - Under 5 years,Number; SEX AND AGE - Total population - 5 to 9 years,Number; SEX AND AGE - Total population - 10 to 14 years,Number; SEX AND AGE - Total population - 15 to 19 years,Number; SEX AND AGE - Total population - 20 to 24 years,Number; SEX AND AGE - Total population - 25 to 29 years,Number; SEX AND AGE - Total population - 30 to 34 years,Number; SEX AND AGE - Total population - 35 to 39 years,Number; SEX AND AGE - Total population - 40 to 44 years,Number; SEX AND AGE - Total population - 45 to 49 years,...,"Number; HOUSING OCCUPANCY - Total housing units - Vacant housing units - For seasonal, recreational, or occasional use",Number; HOUSING OCCUPANCY - Total housing units - Vacant housing units - All other vacants,Number; HOUSING OCCUPANCY - Total housing units - Homeowner vacancy rate (percent) [8],Number; HOUSING OCCUPANCY - Total housing units - Rental vacancy rate (percent) [9],Number; HOUSING TENURE - Occupied housing units - Owner-occupied housing units,Number; HOUSING TENURE - Occupied housing units - Owner-occupied housing units - Population in owner-occupied housing units,Number; HOUSING TENURE - Occupied housing units - Owner-occupied housing units - Average household size of owner-occupied units,Number; HOUSING TENURE - Occupied housing units - Renter-occupied housing units,Number; HOUSING TENURE - Occupied housing units - Renter-occupied housing units - Population in renter-occupied housing units,Number; HOUSING TENURE - Occupied housing units - Renter-occupied housing units - Average household size of renter-occupied units
0,44594.0,45265.0,46922.0,48727.0,43282.0,43051.0,41946.0,42851.0,43585.0,49320.0,...,20659.0,12740.0,3.2,16.2,184888.0,473775.0,2.56,80296.0,196229.0,2.44
1,44594.0,45265.0,46922.0,48727.0,43282.0,43051.0,41946.0,42851.0,43585.0,49320.0,...,20659.0,12740.0,3.2,16.2,184888.0,473775.0,2.56,80296.0,196229.0,2.44
2,44308.0,44608.0,45243.0,47662.0,47456.0,46301.0,43480.0,44924.0,44036.0,48982.0,...,7615.0,14476.0,2.4,11.1,181751.0,449536.0,2.47,86587.0,210807.0,2.43
3,42303.0,42437.0,45016.0,51495.0,55338.0,43766.0,41477.0,43919.0,44467.0,48180.0,...,13319.0,13930.0,2.9,12.0,188537.0,473531.0,2.51,81107.0,190449.0,2.35
4,42793.0,44073.0,45544.0,46281.0,39429.0,39684.0,40384.0,44707.0,45420.0,49398.0,...,8648.0,16542.0,2.3,10.7,200697.0,505242.0,2.52,70620.0,168946.0,2.39

In [24]:
sf1_numbers_short.to_csv('sf1_numbers_1.csv')
sf1_percentages_short.to_csv('sf1_percentages_1.csv')

acs1_numbers_short.to_csv('acs1_numbers_1.csv')
acs1_percentages_short.to_csv('acs1_percentages_1.csv')

social_numbers_short.to_csv('social_numbers_1.csv')
social_percentages_short.to_csv('social_percentages_1.csv')

economic_numbers_short.to_csv('economic_numbers_1.csv')
economic_percentages_short.to_csv('economic_percentages_1.csv')

housing_numbers_short.to_csv('housing_numbers_1.csv')
housing_percentages_short.to_csv('housing_percentages_1.csv')